import Head from 'next/head'
import { Inter } from '@next/font/google'
import NavMenu from '@/components/nav-menu/nav-menu'
import Breadcrumbs from '@/components/breadcrumbs/breadcrumbs'
import { userAPI } from '@/services/UserService'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const {data : users, isLoading, error} = userAPI.useFetchAllUsersQuery(2);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='max-w-5xl m-auto flex flex-col items-center justify-evenly'>
        <NavMenu/>
        <Breadcrumbs/>
        {isLoading && <h1>Loading...</h1>}
        {error && <h1>Loading error</h1>}
        Главная
        {/* {JSON.stringify(users, null, 2)} */}
        ----------
        {JSON.stringify(users, null, 2)}
      </div>
    </>
  )
}
